# vim: fdl=1 ft=sh sw=2:

# ~/.bashrc in an Arch install on my  AsusW202  system
# symlinked in  $bs/anytime/symlinks-jo-0.sh

[[ $- != *i* ]] && return  # if not running interactively, don't do anything

#=> load the rest of my bashrc
source $Bash/bashrc

