# vim: set ft=sh tw=0:

# ~/.bashrc in an Arch install on my Acer Veriton T661 system

# Joseph Harriott  Fri 17 Apr 2020
# source ~/.bashrc if you've changed something here...

export BFG=/mnt/9QG2FFEE/Share-IT-Copied/CrossPlatform/Encoding/Git/bfg-1.13.0.jar
source ~/.bashrc-console

# backup destination for  mwBackup.sh
muttBasckupDestination=/mnt/9QG2FFEE/Share-More/mw-AVT661

if [[ $DROPBOX ]]; then
  source $ARCHBUILDS/jo/Bash/bashrc-email
  source $ARCHBUILDS/jo/Bash/bashrc-images
  source $ARCHBUILDS/jo/Bash/bashrc-ob
fi

alias rs0='bash /mnt/WD1001FALS/rsyncBackup-AVT661/archive-Sync0.sh'
alias rs1='bash /mnt/WD1001FALS/rsyncBackup-AVT661/archive-Sync1.sh'

# NETGEAR WG111v2
doup () {
  sudo ip link set wlwg111v2 down
  sudo ip link set wlwg111v2 up
}
alias d='doup'
alias i='iwctl station wlwg111v2 get-networks'

# virtualenvwrapper
export WORKON_HOME=~/.virtualenvs
source /usr/bin/virtualenvwrapper.sh

# auto-added by $ cpan
PATH="/home/jo/perl5/bin${PATH:+:${PATH}}"; export PATH;
PERL5LIB="/home/jo/perl5/lib/perl5${PERL5LIB:+:${PERL5LIB}}"; export PERL5LIB;
PERL_LOCAL_LIB_ROOT="/home/jo/perl5${PERL_LOCAL_LIB_ROOT:+:${PERL_LOCAL_LIB_ROOT}}"; export PERL_LOCAL_LIB_ROOT;
PERL_MB_OPT="--install_base \"/home/jo/perl5\""; export PERL_MB_OPT;
PERL_MM_OPT="INSTALL_BASE=/home/jo/perl5"; export PERL_MM_OPT;

