# vim: fdl=1 ft=sh sw=2:

# $machBld/jo/Bash/bashrc  symlinked in  $bSc/symlinks/jo-0.sh  e -la ~/.bashrc

[[ $- != *i* ]] && return  # if not running interactively, don't do anything

#=> load the rest of my bashrc
source $Bash/bashrc

