# vim: fdl=1 ft=sh sw=2:

# ~/.bashrc in an Arch install on my  i34G1TU02  system
# symlinked in  $ARCHBUILDS/build-scripts/17-symlinks.sh

[[ $- != *i* ]] && return  # if not running interactively, don't do anything

#=> load the rest of my bashrc
source $Bash/bashrc

