#!/bin/sh
# vim: ft=sh sw=2:

# Joseph Harriott - Thu 15 Jan 2026

# Bash configurations that are also useful in Console and as root.

# $OSAB/nodes-Bash/bashrc-generic  symlinked in  $OSAB/nodes-set/jo-0-Bash-X.sh, then
#  for jo: sourced by  $AjB/bash_profile  &  $AjB/bashrc
#  for root: sourced by  $OSAB/nodes-root/bashrc
# see  $OSAB/nodes/set/repair.sh  for checking if this was sourced

[[ $- == *i* ]] && source -- '/usr/share/blesh/ble.sh' --attach=none --rcfile "$OSAB/nodes-Bash/blerc"
alias fin='figlet -f univers finished'
if [ $host = 'sbMb' ]; then alias f1t2t3="bash ~/Arch/f1t2t3/f1t2t3.sh"; fi
lnd () { [ -d $2 ] && rm -r $2; ln -sf $1 $2; } # symlink a directory
mn () { MANPAGER='nvim +Man!' MANWIDTH=999 man $1; }
source $cITcc/CP/wfxr-code-minimap/completions/bash/code-minimap.bash  # code-minimap ~/.bashrc
source $cITcc/unix-linux/trapd00r-LS_COLORS/lscolors.sh  # fancy colouring, echo "$LS_COLORS"
source $OSL/nodes/bashrc-generic

[ $TERM != 'screen-256color' ] && [[ -z $in_nvim ]] && [ $(logname) == $(whoami) ] && neofetch
# - won't run in  tmux  or after  su

# <esc> <esc> prefixes sudo on last command
source $cITcc/CP/ohmybash-sudo.plugin.sh

ft () {
  if [ "$1" ]; then
    of="$culLB/FIGletFontsTest.txt"
    echo "$1" > $of; echo '' >> $of
    for font in big doh doom isometric1 isometric2 larry3d nancyj-fancy nancyj nancyj-underlined ogre poison puffy radical_ rowancap shadow standard starwars stellar stop straight tombstone trashman ttyb tty univers usaflag utopia xbriteb xttyb; do
      figlet -t -f $font -w 250 "$1" >> $of
      echo "- $font" >> $of
    done
    sed -i 's/ \+$//' $of
    echo "results are in $of"
  else
    echo "ft 'some text'"
  fi
}

# tmux
alias u=tmux
  alias tkt='u kill-server > /dev/null 2>&1; tmux'  # rarely used

#=> awesome  or  Openbox  or Xfce  on a machine
startxa () { ln -sf $ABjo/xinitrcs/awesome ~/.xinitrc; }
startxo () {
  ln -sf $ABjo/xinitrcs/openbox ~/.xinitrc
  ln -sf $machBld/Alacritty/Openbox.toml ~/.alacritty.toml
}
startxx () {
  ln -sf $ABjo/xinitrcs/xfce ~/.xinitrc
  ln -sf $machBld/Alacritty/Xfce.toml ~/.alacritty.toml
  ln -sf $ABjo/wm/Xfce/terminal_startup.sh ~/.startup_terminal.sh
  ln -sf $ABjo/wm/Xfce/config_gtk30_gtk.css ~/.config/gtk-3.0/gtk.css
  # - for  ~/.config/autostart/Alacritty.desktop
  ln -sf $machBld/jo/Conky/Xfce.lua ~/.conkyrc
}

#=> better file managing
alias e='eza --icons'
  alias a='e -aF'  # grid, handily showing up symlinks
  alias es='e -alR'  # show permissions, rough sizes, and symlinks recursively
  alias et='e -T'  # for tree
alias ed='eza -D'  # show directories only
alias edt='eza -DT'  # show directory tree
alias ig='ig --editor nvim'  # igrep

alias l='ls --color=auto'

alias ltd='lsd -d --tree'  # more in  $OSL/bashrc-generic

alias mo='moar'

c() { if [ -n "$1" ]; then cd "$1" || return 1; else cd ..; fi; l -a; }
# - https://superuser.com/a/1244522/242800

export PAGER=less
source $OSL/nodes/bashrc-generic

if [ -s "/usr/bin/broot" ]; then
  source ~/.config/broot/launcher/bash/br  # (first  broot  adds to  .bashrc)
fi # configures broot

if [ -s "/usr/share/fzf" ]; then
  # alias f="fzf --preview 'bat --color=always {} | head -500'"
  alias f="fzf --preview 'bat --color=always {}'"
  eval "$(fzf --bash)"  # key bindings and fuzzy completion
  export FZF_DEFAULT_COMMAND='fd --type f --hidden --follow --exclude .git --no-ignore'
  export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
fi

r () {
  [ $TERM != 'screen-256color' ] && pi="--cmd='set preview_images true'"
  eval "ranger --choosedir=$HOME/.ranger_last_visited $pi $@"
  cd "$(cat $HOME/.ranger_last_visited)"
}  # r "$Drpbx/CAM-best/Classic Yo-Yo"

#==> bat
alias b='bat'  # syntax highlit cat
alias bd='bat -d'  # showing changes from git index
alias bm='batman'  # better manual (in wide enough terminal)
alias pb='prettybat'  # tidied code
export BAT_PAGER=less

#==> system monitoring
alias bt='bashtop'
alias gl='glances'

#==> virtualenvwrapper
export WORKON_HOME=~/.virtualenvs  # $WORKON_HOME
[[ -f /usr/bin/virtualenvwrapper.sh ]] && source /usr/bin/virtualenvwrapper_lazy.sh

#=> clamscan
# $hmlA/ml-$host/cs

#==> 0 scan
scs () {
  cslbn="/home/jo/Arch/cs"
  [ $myDrA ] && cslbn="$hmlA/ml-$host/cs"
  cslmn=$(date '+%y%m%d-%H%M').log  # clamscan log make name
  cslm=~/Arch/clamscan-$cslmn
  echo "about to clamscan /"
  # sudo clamscan -r --exclude-dir='/media|/mnt|/sys' /opt/zoom/ 2>&1 | tee $cslm
  sudo clamscan -r --exclude-dir='/media|/mnt|/sys' $1 2>&1 | tee $cslm
  mv $cslm $cslbn/$cslmn
} # scs /opt/zoom  to test
# end of log shows time taken
# sbMb: scs /  took 21h to scan almost 2m files

#==> 1 filter the results
# $vfv/syntax/cslF.vim

csF () {
  if [ $1 ]; then
    cslF="${1:0:6}-FOUND.cslF"
    # make clamscan FOUND log file - should be enough
    cp $1 $cslF
    sed -i '/ FOUND$/!d' $cslF
    sed -i 's/ FOUND$//' $cslF
    sed -i '1s/^/vim \/Heuristics.Phishing.Email.SpoofedDomain\\|Sanesecurity\\|Urlhaus\n\n/' $cslF
    echo "- now look in  ${tpf7}$cslF${tpfn}"
  else
    echo "- need a clamscan nnnnnn-nnnn.log"
  fi
} # csF <log_file>

#=> internetish
Q () { pacman -Qs $1 | xcol $1; }  # or use  pacsearch

suho () {
  ipnf=$(ip neigh)
  ipn=${ipnf:0:11}
  mapfile -t fi < <(doas fping -g "$ipn.0/24" 2>&1)
  printf '%s\n' "${fi[@]}" | grep 'alive$'
} # subnet hosts

#=> pactree
alias ptc='pactree -c '  # coloured
alias ptr='pactree -cr '  # reversed

pts () { pactree -u $1 | sort | tr '\n' '~' | sed 's/~/  /g'; echo; }  # scrunched

#=> system
plo(){
  plof="$machLg/usr/pip-list-outdated.txt"
  echo > $plof
  echo 'output of plo() ($OSAB/Bash/bashrc-generic)' >> $plof
  echo >> $plof
  pip list --outdated >> $plof
  echo >> $plof
} # takes a while

cgabc () {
  e="$machLg/jo/shell/compgen_abc.txt"
  echo 'vim: fdl=0 ft=build:' > $e; echo '' >> $e
  echo "# aliases" >> $e
  compgen -a | sort | awk '{print}' ORS=' : ' >> $e; echo '' >> $e
  echo "# builtins" >> $e
  compgen -b | sort | awk '{print}' ORS=' : ' >> $e; echo '' >> $e
  echo "# commands" >> $e
  compgen -c | sort | awk '{print}' ORS=' : ' >> $e; echo '' >> $e
}

uf(){
  ufl="$culLAb/ml-$host/usr-files.txt"
  echo 'vim: set nowrap:' > $ufl
  echo >> $ufl
  echo 'output of  uf() ($OSAB/Bash/bashrc-generic)' >> $ufl
  echo >> $ufl
  e -al /usr/* >> $ufl
  echo >> $ufl
} # usr files

usf(){
  usft="$machLg/usr/share/fonts/usf.tree"
  echo 'output of usf() ($OSAB/Bash/bashrc-generic)' > $usft
  echo >> $usft
  tree -l /usr/share/fonts/ >> $usft
  # move count line of  tree
    cl=$(tail -n1 $usft)
    sed -i '$d' $usft
    sed -i "3s/$/ - $cl\n/" $usft
}

#=> turbostat
alias ts1='sudo turbostat --interval 2 --quiet'

ts2 () {
  if [ $TERM == 'linux' ]; then
    echo "not in a resizable window"  # Console
  elif [[ -n $TMUX ]]; then
    echo "now detach tmux and run ts2 again"
    export reattachTmux=ts2
  else
    export reattachTmux=
    tc=109 # columns needed for turbostat
    read rows cols < <( stty size )
    if (( $cols < $tc )); then
      resize -s $rows $tc
    else
      echo "columns already >= $tc"
      sleep 1
    fi
    tmux a
  fi  # tmux
} # widen terminal for turbostat

