#!/bin/sh
# vim: fdl=1 ft=sh sw=2:

# Joseph Harriott

# $OSAB/nodes-Bash/blerc

# ble.sh  configuration - sourced from  $OSAB/nodes-Bash/bashrc-generic

#=> blehook  keymap_vi_load
function my/vi_load {

  # loss of  SIGINT
  # ble-bind -f 'C-c' ''
  # - doesn't help much, so just use  Esc 0 D

  ble-bind -m vi_cmap --cursor 0
  ble-bind -m vi_imap --cursor 5
  ble-bind -m vi_nmap --cursor 2
  ble-bind -m vi_omap --cursor 4
  ble-bind -m vi_smap --cursor 2
  ble-bind -m vi_xmap --cursor 2

  ble-import vim-surround

  bleopt exec_errexit_mark=  # set a value to see  [ble: exit ???]  after a command

  bleopt keymap_vi_mode_show=  # set a value to see  -- INSERT --  below the prompt
    bleopt keymap_vi_mode_name_insert='i'
    bleopt keymap_vi_mode_name_replace='r'
    bleopt keymap_vi_mode_name_vreplace='vr'
    bleopt keymap_vi_mode_name_visual='v'
    bleopt keymap_vi_mode_name_select='s'
    bleopt keymap_vi_mode_name_linewise='l'
    bleopt keymap_vi_mode_name_blockwise='b'
    bleopt keymap_vi_mode_string_nmap=$'\e[1m-- n --\e[m'
}
blehook/eval-after-load keymap_vi my/vi_load

