#!/bin/sh
# vim: ft=sh sw=2:

# $OSAB/nodes-Bash/export-Arch
# here I export variables that could also be useful as root

# Variable naming constraints:
#  avoid names that only differ by case
#  use names that grep unambiguously throughout all of my notes directories

# After $machBld/Bash_start,
#  for initial build of Arch:
#    rsync -irtv --delete --modify-window=1 /run/media/jo/K16GBDTG2/Dr-IT/core/onGitHub/ $HOME/onGH
#  for jo:
#   symlinked in  $OSAB/nodes-set/jo-0-Bash-X.sh
#    then sourced by  $AjB/bash_profile
#  for root:
#   symlinked in  $OSAB/nodes-set/root.sh
#    then sourced by  $OSAB/nodes-root/bash_profile

export thb="/home/jo/.thunderbird" # $thb

#=> 0 mail
export maild=/home/jo/.local/share/mail  # $maild  for  mutt

#=> 1 host
[[ $archiso ]] || export host=$(uname -n) # $host

#=> 2 $Drpbx, or not
if [[ $myDrA == 1 ]]; then
  # $myDrA, $Storage  defined in  $machBld/export-machine
  export Drpbx=$Storage/Dropbox
    export DrJo=$Drpbx/Jo
    export ITcore=$Drpbx/IT/core
      export culL=$ITcore/ulLinux
        export culLA="$culL/Arch"
          export machLg=$culLA/ml-$host  # as opposed to  $machBld
        export culLB=$culL/Bash  # rg -l '\$culLB' $ITcore
      export culLAb="$ITcore/ulLinuxArch-big" # rg -l '\$culLAb' $ITcore
      export ITccl=$ITcore/copied-linked  # $ITccl
      export onGH=$ITcore/onGitHub
else
  # Building  root / user:
    if [ -d /home/jo/onGh ]; then
      export onGH=/home/jo/onGH
    else
      export onGH=/root/onGH
    fi
fi

#=> 4 rooting on  $onGH
export OSAB=$onGH/OS-ArchBuilds
  export ABjo=$OSAB/nodes-jo
    export AjB=$ABjo/Bash
    export BAT_CONFIG_PATH="$ABjo/bat.conf"  # for the bat pager
  export machBld=$OSAB/mb-$host  # $machBld  as opposed to  $machLg  /machLg=
export OSL=$onGH/OS-Linux
  export clMail="$OSL/nodes/jo/clm" # used in  $clMail  &  $OSL/nodes/bashrc-clm
    export clMn=$clMail/neomutt  # $clMn
export vimfiles=$onGH/vimfiles

