#!/bin/sh
# vim: ft=sh sw=2:

# $OSAB/nodes-Bash/export-storage
# here I export variables that could also be useful as root

# Variable naming constraints:
#  avoid names that only differ by case
#  use names that grep unambiguously throughout all of my notes directories

# for initial build of Arch (after $machBld/export-machine):
# for jo:
#  symlinked in  $OSAB/nodes-set/jo-0-Bash-X.sh
#   then sourced by  $AjB/bash_profile
# for root:
#  symlinked in  $OSAB/nodes-set/root.sh
#   then sourced by  $OSAB/nodes-root/bash_profile

#=> 0 core
# $myDrA  &  $Storage  are pre-defined in  $machBld/export-machine

#=> 0 mail
export maild=/home/jo/.local/share/mail  # $maild  for  mutt

#=> 1 host
export host=$(uname -n) # $host

#=> 2 $Drpbx, or not
export vimfiles=~/.vim
if [[ $myDrA == 1 ]]; then
  export Drpbx=$Storage/Dropbox
    export DJH=$Drpbx/JH
    # - keep  DROPBOX  capitalised for finding it without need for $
      export core=$DJH/core
        export coreIT=$core/IT
          export CrPl=$coreIT/CP  # $ITsCP  used in  $AjB/bashrc-console  & build scripts
          export onGH=$coreIT/onGitHub
            export vimfiles=$onGH/vimfiles
          export culL=$coreIT/ulLinux
            export culLA=$culL/Arch
              export machLg=$culLA/ml-$host  # as opposed to  $machBld
            export culLB=$culL/Bash  # $culLB  used in  $OSAB/QR/QR.md
          export culLAb="$coreIT/ulLinuxArch-big" # $culLAb
          export hmlA="$coreIT/ulLinuxArch-huge" # $hmlA
fi  # depends on  myDrA=  defined in  $machBld/export-machine

#=> 3 (rooting on $onGH) $OSAB, $OSL, and some build dependencies
unset OSAB, OSL
if [ $onGH ]; then
  export OSAB=$onGH/OS-ArchBuilds
  export OSL=$onGH/OS-Linux
else
  AB=~/OS-ArchBuilds; [ -d $AB ] && export OSAB=$AB
  hjAB=/home/jo/OS-ArchBuilds; [ -d $hjAB ] && export OSAB=$hjAB
fi  # depends on  onGH=
export clMail="$OSL/nodes/jo/clm" # used in  $clMail  &  $OSL/nodes/bashrc-clm
  export clMn=$clMail/neomutt  # $clMn
if [ $OSAB ]; then
  export ABjo=$OSAB/nodes-jo
    export AjB=$ABjo/Bash
    export BAT_CONFIG_PATH="$ABjo/bat.conf"  # for the bat pager
  export machBld=$OSAB/mb-$host  # $machBld  as opposed to  $machLg
fi

