#!/bin/bash
# vim: fdl=1 ft=sh sw=2:

# $OSAB/mb-HPEB840G3x/8/Bash_start
#  machine-specific exports that could also be useful as root

# for jo:
#  symlinked in  $OSAB/nodes-set/jo-0-Bash-X.sh
#   then sourced by  $AjB/bash_profile
# for root:
#  symlinked in  $OSAB/nodes-set/root-0.sh
#   then sourced by  $OSAB/nodes-root/bash_profile

export rsnapshot=a_portable_drive  # $rsnapshot
export startxDelay=5

#=> for  $OSAB/nodes-Bash/export-Arch
# 0 during initial build, before  $Drpbx:
export user_jo=1  # only when user  jo  is active
  # for  $OSAB/nodes-Bash/export-Arch, because [ -d /home/jo/onGh ] fails from  ~/.bash_profile
  # once set and integrated into  /root, can  rm -r /root/onGH

# 1 once  $Drpbx:
# export myDrA=1  # $myDrA, only when my Dropbox is active

# 2 Machine:
export Storage=/mnt/MZNLN128  # $Storage, where I keep stuff
  export Enc=$Storage/encrypted  # mkdir $Enc

