#!/bin/bash
# vim: fdl=1 ft=sh sw=2:

# $machBld/Bash_start - machine-specific exports that could also be useful as root

# for jo:
#  symlinked in  $OSAB/nodes-set/jo-0-Bash-X.sh
#   then sourced by  $AjB/bash_profile
# for root:
#  symlinked in  $OSAB/nodes-set/root.sh
#   then sourced by  $OSAB/nodes-root/bash_profile

export rsnapshot=a_portable_drive  # $rsnapshot
export startxDelay=5

#=> for  $OSAB/nodes-Bash/export-Arch
# export myDrA=1  # only when my Dropbox is active
export Storage=/mnt/MZNLN128  # $Storage, where I keep stuff
  export Enc=$Storage/encrypted  # mkdir $Enc

