# vim: fdl=1 ft=systemd:

# $ABno/etc/systemd/override.conf
#  cp'd  in  my  $OSAB/bs-2-to_X/1-sudo-autoLoginTTY.sh
#  still used in  sbMb, but superseded by  $ABno/etc/systemd/autologin.conf

[Service]
ExecStart=
ExecStart=-/usr/bin/agetty --autologin jo --noclear %I $TERM

