
# $machBld/jo/term/kitty.conf ($OSAB/nodes-set/jo-3-when_myDrA.sh)

# see  /usr/share/doc/kitty/kitty.conf

# Fonts:
font_family      family="UbuntuMono Nerd Font Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 9.0

