#!/bin/bash
# vim: fdl=1 ft=sh sw=2:

# $ABnm/Bash_start ($OSAB/nodes-set/shell.sh)
#  machine-specific exports that could also be useful as root

# for jo: sourced by  $AjB/bash_profile
# for root: sourced by  $OSAB/nodes-root/bash_profile

export rsnapshot=/run/media/jo/S14JJ9CP956373/rsnapshot  # $rsnapshot
export startxDelay=5

#=> for  $ABno/Bash/export-Arch
# 0 during initial build, before  $Drpbx:
export user_jo=1  # only when user  jo  is active
  # because [ -d /home/jo/onGh ] fails from  ~/.bash_profile
  # once set and integrated into  /root, can  rm -r /root/onGH

# 1 once  $Drpbx:
export myDrA=1  # $myDrA, only when my Dropbox is active

# 2 Machine:
export Storage=/mnt/MZNLN128  # $Storage, where I keep stuff
  export Enc=$Storage/encrypted  # mkdir $Enc

