
# Alacritty - $machBld/alacritty.toml ($OSAB/nodes-set/jo-0.sh)
#  importing  $OSAB/nodes/alacritty-all.toml

[font]
  size = 7  # change is instantaneous

[general]
  import = [ "~/.alacritty-all.toml" ]

