#!/bin/bash
# vim: fdl=1 ft=sh:

# $machBld/export-machine - machine-specific exports that could also be useful as root

# for jo:
#  symlinked in  $bSc/symlinks/jo-0.sh
#  sourced by  $Bash/bash_profile
# for root:
#  symlinked in  $bSc/05-root_symlinks.sh
#  sourced by  $OSAB/root/bash_profile

export rsnapshot=/mnt/ST4000VN008/rsnapshot
export startxDelay=5

#=> for  $OSAB/Bash/export-storage
export Enc=/mnt/SD480GSSDPlus/Encrypted  # $Enc
export myDrA=1  # only when my Dropbox is active
export Storage=/mnt/SDU3D1TB  # where I keep stuff

