#!/bin/bash
# vim: fdl=1 ft=sh:

# $machBld/export-machine - machine-specific exports that could also be useful as root

# for jo:
#  symlinked in  $OSAB/nodes-set/jo-0-Bash-X.sh
#   then sourced by  $AjB/bash_profile
# for root:
#  symlinked in  $OSAB/nodes-set/root.sh
#   then sourced by  $OSAB/nodes-root/bash_profile

export CopIT='/mnt/WD20EZAZ/Cop-IT'  # $CopIT
export OBSmkvGrabs='/mnt/ST4000VN008/OBSmkvGrabs'
export rsnapshot='/mnt/ST4000VN008/rsnapshot'  # $rsnapshot
export startxDelay=5

#=> for  $OSAB/nodes-Bash/export-storage
export Enc=/mnt/SD480GSSDPlus/Encrypted  # $Enc
export myDrA=1  # only when my Dropbox is active
export Storage=/mnt/SDU3D1TB  # $Storage, where I keep stuff

