#!/bin/sh

# symlinked in  $OSAB/nodes-set/jo-0.sh  to  ~/.xinitrc

source $ABjo/xinitrcs/xinitrc  # calls  $ABjo/wm/Xresources/Xresources (~/.Xresources)

## awesome
exec /usr/bin/awesome >> ~/.cache/awesome/stdout 2>> ~/.cache/awesome/stderr

