#!/bin/sh

# symlinked in  $bs/anytime/symlinks-jo.sh  to  ~/.xinitrc

source $ARCHBUILDS/jo/xinitrcs/xinitrc  # calls $MACHINE/jo/Xresources

## awesome
exec /usr/bin/awesome >> ~/.cache/awesome/stdout 2>> ~/.cache/awesome/stderr

