#!/bin/sh

# symlinked in  $bSc/anytime/symlinks-jo.sh  to  ~/.xinitrc

source $ABjo/xinitrcs/xinitrc  # calls $machBld/jo/Xresources

## Openbox
exec openbox-session  # accesses  ~/.config/openbox/autostart

