#!/bin/bash
# vim: fdl=1 ft=sh:

# symlinked in  $ARCHBUILDS/build-scripts/17-symlinks.sh
# sourced by  $Bash/bash_profile

export rsnapshot=/mnt/KDTG311281/rsnapshot
export Storage=/mnt/SDEP128G  # where I keep stuff

# Used in  $Openbox/openbox/urxvtl.sh
# open urxvt from left of screen, allowing room for 106 column gVim
# export urxvtGeometry='92x54+0+0'  # 1440x900 screen
export urxvtGeometry='105x67+0+0'  # 1920x1080 screen:  urxvt -geometry '105x67+0+0' &

