# vim: fdl=1 ft=sh sw=2:

# $Bash/bashrc, sourced by  $machBld/jo/Bash/bashrc

#=> load the rest of my bashrc
source ~/.bashrc-generic  # useful everywhere, including root
source ~/.bashrc-console  # ($Bash/bashrc-console) useful also in Console as user
source $Bash/bashrc-clm  # can be used before WM
source $Bash/bashrc-wm
source $Bash/bashrc-ob  # useful in Openbox (and awesome)

