#!/bin/sh
# vim: fdl=1 ft=sh:

# ~/.export-jo  ($Bash/export-jo)
#  depends on  $OSAB/Bash/export-storage
#  sourced by  $Bash/bash_profile
#  symlinked in  $OSAB/bs-symlinks/jo-0.sh

export MANPATH=/usr/share/man/
uG="$machBld/jo/Bash/exportWS"; [[ -f $uG ]] && source $uG

export MOZ_GTK_TITLEBAR_DECORATION=client
export PAPERSIZE=A4  # libpaper

#=> storage
# here I'm taking care to avoid variables that only differ by case

export CPdoc=$CrPl/documenting
    export LTXj=$CPdoc/LaTeX/jo  # $LTXj
export Imagey=$Bash/Imagey  # used in  $Bash/bashrc-wm
export lazy="$HOME/.local/share/nvim/lazy"  # $lazy - neovim  plugins
export lclm=$ulL/clm  # $lclm  linux command-line mail, was  GNULE
export Openbox=$ABjo/wm/Openbox
    export Obc=$Openbox/openbox  # $Obc - configurations
export TeNo=$core/TextNotes  # used in  $TeNo
    export TNt=$TeNo/tex  # *.tex's - used in  $Bash/bashrc-wm

#==> rooting on $Drpbx
export COT=$Drpbx/Cop/OutThere  # $COT  used in  $TeNo
export DCGRs=$Drpbx/Cop/GRs
    # - Dropbox Copied Git Repositories, used in  $OSAB/bs-symlinks/jo-1-awesome.sh
    [ -d "$DCGRs" ] || export DCGRs=~/DCGRs  # when building Arch
    export jkll=$DCGRs/CP/Ruby/Jekyll
        export mnm=$jkll/Jekyll-jekyll-minima

#==> rooting on $DJH
export CfWk=$DJH/Cop-work
    export ScEn=$CfWk/education/Science-Engineering
export Cfzd=$DJH/work-Cz
    export CzMa=$Cfzd/manage  # $CzMa
    export CzPeo=$Cfzd/people  # $CzPeo
        export Copil=$CzPeo/adherents/FA+Copil  # $Copil
    export CzPhy=$Cfzd/PhysicalProperty  # $CzPhy
export JCop=$DJH/Cop  # used in  $TeNo
    export cFr=$JCop/France  # $cFr  used in  $TeNo
    export chum=$JCop/human  # used in  $TeNo
        export chin=$chum/ingest  # $chin  used in  $TeNo
    export copOT=$JCop/OutThere  # $copOT  used in  $TeNo
    export Pr0=$JCop/Practical0
        export Pr0t=$Pr0/technos  # $Pr0t
export DaLi=$DJH/Jo-now/DailyLife  #  $DaLi  used in  $TeNo
export ess=$DJH/Jo-now/essential
    export eFr=$ess/France  # $eFr
    export hlth=$ess/health  # $hlth
    export Sig=$ess/signatures  # $Sig  for use in creating documents
export FrFa=$DJH/Jo-F+F
    export FFIdF=$FrFa/France/IdF  # $FFIdF  used in  $TeNo
export JHt=$DJH/Jo-technos
    export jtIT=$JHt/IT  # used in  $core  &  $jtIT
        export jtCP=$jtIT/CP  # $jtCP
        export jtUL=$jtIT/UnixLike  # $jtUL  used in  $core  &  $jtIT
    export tIs=$JHt/IT-storage  # $tIs/diskUsage.txt
export JHw=$DJH/work  # $JHw - for IT websites and more
    export atone=$JHw/WB-Hugo-atiavda_one  # $atone
    export bilan=$JHw/ST/LPD/IdF/AB-TAP/bilan
    export JHm=$JHw/IT-Jekyll-harriott-minima  # $JHm
    export rEr=$JHw/France/IdF/Paris/20e-rueErmitage
          export StEr=$rEr/StudioErmitage  # $StEr
export Thb=$DJH/Thb-dr  # $Thb, used in
                        #  $ABjo/wm/TS/locks.sh
                        #  $OSAB/bs-4-whenWM/4-various.sh
                        #  $OSAB/jo/wm/TS/thunderbird_safely.sh
                        #  ~/.thunderbird/profiles.ini
export JJt0=$DJH/Jo-then0  # used in  $TeNo
    export T0Fr=$JJt0/Europe/France  # $T0Fr  used in  $TeNo

#==> rooting on $ITstack
export DWp=$ITstack/DokuWiki/pages  # $DWp
export ITscc=$ITstack/copied-code  # $ITscc  - needed resources
export ITscr=$ITstack/copied-reference  # handy
    export ITsrul=$ITscr/unix-like  # $ITsrul

#==> rooting on $onGH
export MD4PDF=$onGH/pandoc-md4pdf  # $MD4PDF  is unambiguous
export misc=$onGH/misc  # $misc
export MSWin10=$onGH/OS-MSWin10  # $MSWin10  used in  $DWp  &  $TeNo
export OSAT=$onGH/OS-Android-Termux  # $OSAT
export vimfiles=$onGH/vimfiles
    [ -d "$onGH" ] || export vimfiles=~/vimfiles  # when building Arch
    export vfvp="$vimfiles/vim/packs"  # $vfvp

