#!/bin/sh
# vim: fdl=1 ft=sh sw=2:

# ~/.export-jo  ($Bash/export-jo)
#  depends on  $ARCHBUILDS/Bash/export-storage
#  sourced by  $Bash/bash_profile
#  symlinked in  $bSc/anytime/symlinks-jo-0.sh

export MANPATH=/usr/share/man/
uG=$machBld/jo/Bash/export-urxvt; [[ -f $uG ]] && . $uG

export MOZ_GTK_TITLEBAR_DECORATION=client

# export GIT_PS1=$(__git_ps1 " (%s)")
# - excruciatingly slow on a huge repository such as  nerd-fonts

#=> storage
# here I'm taking care to avoid variables that only differ by case

export bilan=$Drpbx/JH/Work/ST/LPD/IdF/AB-TAP/bilan
export Cfzd=$Drpbx/JH/Cafezoide
export copied=$Drpbx/JH/copied  # used often in  $TeNo
  export cITh=$copied/IT-handy
    export cIThul=$cITh/unix-like
    export GHrCl=$Storage/IT-Copied/GHrepos  # GitHub Repositories Clone
    export GHrUse=$cITh/GHrepos  # GitHub Repositories Use
    [ -d "$GHrUse" ] || export GHrUse=~/GHrUse
export Imagey=$Bash/Imagey  # used in  $Bash/bashrc-wm
export IT1=$Drpbx/JH/technos/IT1  # for notes
export ITP=$Drpbx/JH/technos/IT0-storage  # $ITP/diskUsage.txt
export lclm=$ulLinux/clm  # linux command-line mail, was GNULE
export MD4PDF=$onGH/md4pdf
export MSWin10=$onGH/MSWin10  # for notes
export Openbox=$ABjo/wm/Openbox
export PAPERSIZE=A4
export ScEn=$Drpbx/JH/CforWork/Education/Science-Engineering  # for notes (:%s/SE/ScEn/g)
export StEr=$Drpbx/JH/work/France/IdF/Paris/rueErmitage/StudioErmitage  # previously used  $detail
export Sig=$Drpbx/JH/now/essential/signatures  # for use in creating documents
export T91=$Drpbx/JH/T91-default-release
export TeNo=$core/TextNotes  # used in my personal notes
  export LTX=$TeNo/TN/LTX  # Landscape TeXs - used in  $Bash/bashrc-wm
export vimfiles=$onGH/vimfiles

