#!/bin/bash
# vim: ft=sh:

# here I export variables that could also be useful as root

# for jo:
#  symlinked in  $ARCHBUILDS/build-scripts/17-symlinks.sh
#  sourced by  $Bash/bash_profile
# for root:
#  symlinked in  $ARCHBUILDS/build-scripts/05-root_symlinks.sh
#  sourced by  $ARCHBUILDS/root/bash_profile

export rsnapshot=/run/media/jo/KDTG311281/rsnapshot/
export startxDelay=2

# machine-specific, for  $ARCHBUILDS/jo/export-storage
export myDrA=0  # 1 when my Dropbox is active
export Storage=/mnt/SDEP128G  # where I keep stuff
    export Enc=$Storage/Encrypted

