#!/bin/bash
# vim: ft=sh:

# here I export variables that could also be useful as root

# for jo:
#  symlinked in  $bs/17-symlinks.sh
#  sourced by  $Bash/bash_profile
# for root:
#  symlinked in  $bs/05-root_symlinks.sh
#  sourced by  $ARCHBUILDS/root/bash_profile

export startxDelay=2

# machine-specific, for  $ARCHBUILDS/Bash/export-storage
# export myDrA=1  # only when my Dropbox is active
export Storage=/mnt/SDEP128G  # where I keep stuff
    export Enc=$Storage/Encrypted

