# vim: set ft=sh tw=0:

# ~/.bashrc in an Arch install on my Acer Veriton T661 system

# Joseph Harriott  http://momentary.eu/  Fri 24 May 2019
# source ~/.bashrc if you've changed something here...

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# ----------------------
# my preferences:
# ----------------------

# a colorised (bold blue) prompt, with git support
source /usr/share/git/completion/git-prompt.sh
GIT_PS1_SHOWDIRTYSTATE=true
GIT_PS1_SHOWUNTRACKEDFILES=true
PS1='\[\e[1;34m\][\w$(__git_ps1 " (%s)")]\$\[\e[0m\] '

# Command not found hook
source /usr/share/doc/pkgfile/command-not-found.bash

# for broot
if [ -s "/usr/bin/moar" ]; then
  export PAGER=moar
else
  export PAGER=less
fi

# for tmux
export EDITOR=nvim
export VISUAL=nvim

# History
alias h='history'
export HISTCONTROL=ignoreboth:erasedups
export HISTFILESIZE=10000
export HISTIGNORE='?:??'
export HISTSIZE=1000
PROMPT_COMMAND='history -a'
shopt -s histappend

source ~/.bashrc-files
source ~/.bashrc-images

# Internetish
alias i='iwctl station wlwg111v2 get-networks'
alias p='ping -c 3 8.8.8.8'
alias pqs='pacman -Qs'

doup () {
  sudo ip link set wlwg111v2 down
  sudo ip link set wlwg111v2 up
}

# email
source $GNULE/mymuttrcAddresses
nmnew () { echo "notmuch new:"; notmuch new; }
msf () { mbsync fm    ; nmnew ; echo "nmTags-fm.sh"    ; bash $hje/nmTags-fm.sh    ; }
msg () { mbsync gmail ; nmnew ; echo "nmTags-gmail.sh" ; bash $hje/nmTags-gmail.sh ; }
msl () { mbsync live  ; nmnew ; echo "nmTags-live.sh"  ; bash $hje/nmTags-live.sh  ; }
msx () { mbsync gmx   ; nmnew ; echo "nmTags-gmx.sh"   ; bash $hje/nmTags-gmx.sh   ; }
alias ms='echo -e "\e[1m\e[95m-- fm --\e[0m"; msf; echo -e "\e[1m\e[95m-- gmail --\e[0m"; msg; echo -e "\e[1m\e[95m-- gmx --\e[0m"; msx; echo -e "\e[1m\e[95m-- live --\e[0m"; msl'
alias nmf='neomutt -F $hje/muttrc-ftml'
alias nmg='neomutt -F $hje/muttrc-gmail'
alias nml='neomutt -F $hje/muttrc-live'
alias nmx='neomutt -F $hje/muttrc-gmx'

# System
export GPG_TTY=$(tty)

# data only if not in tmux
if [ ! $TERM == "screen" ]; then
  neofetch
fi

# virtualenvwrapper
export WORKON_HOME=~/.virtualenvs
source /usr/bin/virtualenvwrapper.sh

