#!/bin/sh

# $ABjo/xinitrcs/awesome
#  symlinked in
#   $OSAB/nodes-Bash/bashrc-generic
#   $OSAB/nodes-set/jo-0-Bash-X.sh

source $ABjo/xinitrcs/xinitrc  # calls  $ABjo/wm/Xresources/Xresources

## awesome
exec /usr/bin/awesome >> ~/.cache/awesome/stdout 2>> ~/.cache/awesome/stderr

