#!/bin/sh

# $ABjo/xinitrcs/openbox
#  symlinked in 
#   $OSAB/nodes-Bash/bashrc-generic
#   $OSAB/nodes-set/jo-0-Bash-X.sh

source $ABjo/xinitrcs/xinitrc  # calls  $machBld/jo/Xresources

## Openbox
export QT_QPA_PLATFORMTHEME=qt5ct  # QPA set here so qt5ct works from Openbox Menu too
[ -f usr/bin/xbindkeys ] && xbindkeys  # must be before launching Openbox
exec openbox-session  # accesses  ~/.config/openbox/autostart

