#!/bin/sh

# $ABjo/xinitrcs/xfce
#  symlinked in 
#   $OSAB/nodes-Bash/bashrc-generic
#   $OSAB/nodes-set/jo-0-Bash-X.sh

source $ABjo/xinitrcs/xinitrc  # calls  $ABjo/wm/Xresources/Xresources

## Xfce
exec startxfce4

