#!/bin/sh

# $ABjo/xinitrcs/xfce
#  symlinked in
#   $OSAB/nodes-Bash/bashrc-generic
#   $OSAB/nodes-set/jo-0-Bash-X.sh

if [[ $ABjo ]]; then
    source $ABjo/xinitrcs/xinitrc  # calls  $ABjo/wm/Xresources/Xresources
else
    echo '$ABjo undefined!'
fi

## Xfce
exec startxfce4

