#!/bin/sh

# JH note:
#  called by
#   $ABjo/xinitrcs/awesome
#   $ABjo/xinitrcs/openbox
#   $ABjo/xinitrcs/xfce
#   so that it is used instead of the default
#  I built this from default, with my additions marked JH.
#  nvim -O /etc/X11/xinit/xinitrc $ABjo/xinitrcs/xinitrc

# -----------------------------------------------
# copied from the default  /etc/X11/xinit/xinitrc
# -----------------------------------------------
userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# twm &
# xclock -geometry 50x50-1+1 &
# xterm -geometry 80x50+494+51 &
# xterm -geometry 80x20+494-0 &
# exec xterm -geometry 80x66+0+0 -name login

# ------------
# JH additions
# ------------
# e -la ~/.Xresources*

# stop the 600s screensaver
xset s off

