" ----------------------------------------------------------------------------
" this is a pointer, on a GNU+Linux system, to my more portably located gvimrc
" ----------------------------------------------------------------------------
source $HOME/.vim/gvimrc-Arch-AVT661.vim

