# vim: fdl=1 ft=sh sw=2:

# $ABno/m-HPEB840G3x/jo/bashrc ($OSAB/nodes-set/jo-0-Bash-X.sh)

[[ $- != *i* ]] && return  # if not running interactively, don't do anything

#=> load the rest of my bashrc
source $AjB/bashrc

