#!/bin/bash
# vim: fdl=2 ft=sh:

# $machBld/jo/Bash/exportWS

# called by  $AjB/export-jo
# definitions here are used in
#  $Obc/autostart/terminal_launch.sh
#  $Obc/rc/rc_xml-mb_make.sh

#=> set  Alacritty  window
export Awp='window.position={x=5,y=5}'  # used in  $Obc/autostart/terminal_launch.sh

#==> 1440x900
export Awd='window.dimensions={columns=67,lines=64}'
# - columns:
#    67 is obviously too narrow, but allows  my  Neovide  with  Conky visible
#   110 allows my  gVim/Neovide

#==> 1680x1050
export Awd='window.dimensions={columns=106,lines=75}'
# - allows  Neovide alongside while still seeing Conky

#=> set  Neovide  window
export Nvdg='--grid 109x59'  # 1440x900  monitor
export Nvdg='--grid 109x70'
# UbuntuMono_Nerd_Font_Mono:  h9:59
# $Nvdg  used in
#  $Obc/autostart/autostart
#  $Obc/rc/rc_xml-mb_make.sh

#=> set  urxvt  geometry appropriate for 1440x900 monitor
# open urxvt from left of screen, allowing room for 106 column gVim
export urxvtGeometry='104x64+0+0'  # urxvt -geometry '104x64+0+0' &
# for  ubuntumono 9  in  $Openbox/Xresources/Xresources

