#!/bin/bash
# vim: fdl=3 ft=sh:

# $machBld/jo/Bash/exportWS

# called by  $AjB/export-jo
# definitions here are used in
#  $Obc/autostart/terminal_launch.sh
#  $Obc/rc/rc_xml-mb_make.sh

#=> set  Alacritty  window
export Awp='window.position={x=5,y=5}'
# used in  $ABjo/wm/terminal/startup.sh

#==> for screens
# depending on font set in  $OSAB/nodes-terminal/alacritty-all.toml

#===> 1440x900
export Awd='window.dimensions={columns=67,lines=64}'
# - columns:
#    67 is obviously too narrow, but allows  my  Neovide  with  Conky visible
#   110 allows my  gVim/Neovide

#===> 1680x1050
export Awd='window.dimensions={columns=106,lines=75}'
# - allows  Neovide alongside while still seeing Conky

#===> 1920x1080 Dell E2214HB monitor
export Awd='window.dimensions={columns=100,lines=72}' # Openbox
export Awd='window.dimensions={columns=126,lines=77}' # Xfce
# - allows  Neovide alongside while still seeing Conky

#=> set  Neovide  window
# export Nvdg='--grid 109x59'  # 1440x900 monitor
export Nvdg='--grid 109x68'  # 1920x1080 Dell E2214HB monitor, only 65 lines of buffer
# export Nvdg='--grid 109x70'  # 1680x1050 monitor (Philips 220V4L), 67 lines of buffer
# UbuntuMono_Nerd_Font_Mono:  h9:59
# $Nvdg  used in
#  $Obc/autostart/autostart
#  $Obc/rc/rc_xml-mb_make.sh

#=> set  urxvt  geometry appropriate for 1440x900 monitor
# open urxvt from left of screen, allowing room for 106 column gVim
export urxvtGeometry='104x64+0+0'  # urxvt -geometry '104x64+0+0' &
# for  ubuntumono 9  in  $Openbox/Xresources/Xresources

