
" $ABjo/textEdit/Vim/vimrc  symlinked in  $bSc/symlinks/jo-0.sh

" move on to my Arch vimrc
let vimrcArch = expand("$HOME/.vim/vimrc-Arch.vim")
if filereadable(vimrcArch)
  exec "source ".vimrcArch
endif " ignored if ~/.vim isn't yet there

