#!/bin/bash
# vim: fdl=1 ft=sh:

# machine-specific exports that could also be useful as root

# for jo:
#  symlinked in  $bSc/anytime/symlinks-jo-0.sh
#  sourced by  $Bash/bash_profile
# for root:
#  symlinked in  $bSc/05-root_symlinks.sh
#  sourced by  $ARCHBUILDS/root/bash_profile

export csm=i34G1TU02-clamscan
export rsnapshot=/run/media/jo/KDTG311282/rsnapshot/
export startxDelay=5

#=> for  $ARCHBUILDS/Bash/export-storage
export myDrA=1  # only when my Dropbox is active
export Storage=/mnt/BX200  # where I keep stuff

