# vim: set ft=sh tw=0:

# ~/.bashrc in an Arch install on my Acer Veriton T661 system

# Joseph Harriott  Fri 17 Apr 2020
# source ~/.bashrc if you've changed something here...

source ~/bashrc-console

# backup destination for  mwBackup.sh
muttBasckupDestination=/mnt/9QG2FFEE/Share-More/mw-AVT661

doup () {
  sudo ip link set wlwg111v2 down
  sudo ip link set wlwg111v2 up
}
alias d='doup'

if [[ $DROPBOX ]]; then
  source $DROPBOX/$ARCHBUILDS/jo/bashrc-email
  source $DROPBOX/$ARCHBUILDS/jo/bashrc-images
  source $DROPBOX/$ARCHBUILDS/jo/bashrc-ob
fi

# virtualenvwrapper
export WORKON_HOME=~/.virtualenvs
source /usr/bin/virtualenvwrapper.sh

# auto-added by $ cpan
PATH="/home/jo/perl5/bin${PATH:+:${PATH}}"; export PATH;
PERL5LIB="/home/jo/perl5/lib/perl5${PERL5LIB:+:${PERL5LIB}}"; export PERL5LIB;
PERL_LOCAL_LIB_ROOT="/home/jo/perl5${PERL_LOCAL_LIB_ROOT:+:${PERL_LOCAL_LIB_ROOT}}"; export PERL_LOCAL_LIB_ROOT;
PERL_MB_OPT="--install_base \"/home/jo/perl5\""; export PERL_MB_OPT;
PERL_MM_OPT="INSTALL_BASE=/home/jo/perl5"; export PERL_MM_OPT;

