# vim: set ft=sh tw=0:

# ~/.bashrc in an Arch install on my Acer Veriton T661 system

# Joseph Harriott  http://momentary.eu/  Fri 24 May 2019
# source ~/.bashrc if you've changed something here...

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# ----------------------
# my preferences:
# ----------------------

# a colorised (bold blue) prompt, with git support
source /usr/share/git/completion/git-prompt.sh
GIT_PS1_SHOWDIRTYSTATE=true
GIT_PS1_SHOWUNTRACKEDFILES=true
PS1='\[\e[1;34m\][\w$(__git_ps1 " (%s)")]\$\[\e[0m\] '

# Command not found hook
source /usr/share/doc/pkgfile/command-not-found.bash

# for broot
if [ -s "/usr/bin/moar" ]; then
  export PAGER=moar
else
  export PAGER=less
fi

# for tmux
export EDITOR=nvim
export VISUAL=nvim

# History
alias h='history'
export HISTCONTROL=ignoreboth:erasedups
export HISTFILESIZE=10000
export HISTIGNORE='?:??'
export HISTSIZE=1000
PROMPT_COMMAND='history -a'
shopt -s histappend

source $DROPBOX/$AVT661/jo/Bash/bashrc-email
source $DROPBOX/$AVT661/jo/Bash/bashrc-files
source $DROPBOX/$AVT661/jo/Bash/bashrc-images

# Internetish
alias i='iwctl station wlwg111v2 get-networks'
alias p='ping -c 3 8.8.8.8'
alias pqs='pacman -Qs'

doup () {
  sudo ip link set wlwg111v2 down
  sudo ip link set wlwg111v2 up
}

# System
export GPG_TTY=$(tty)

# data only if not in tmux
if [ ! $TERM == "screen" ]; then
  neofetch
fi

# virtualenvwrapper
export WORKON_HOME=~/.virtualenvs
source /usr/bin/virtualenvwrapper.sh

# auto-added by $ cpan
PATH="/home/jo/perl5/bin${PATH:+:${PATH}}"; export PATH;
PERL5LIB="/home/jo/perl5/lib/perl5${PERL5LIB:+:${PERL5LIB}}"; export PERL5LIB;
PERL_LOCAL_LIB_ROOT="/home/jo/perl5${PERL_LOCAL_LIB_ROOT:+:${PERL_LOCAL_LIB_ROOT}}"; export PERL_LOCAL_LIB_ROOT;
PERL_MB_OPT="--install_base \"/home/jo/perl5\""; export PERL_MB_OPT;
PERL_MM_OPT="INSTALL_BASE=/home/jo/perl5"; export PERL_MM_OPT;

