# vim: set ft=sh tw=0:
#
# ~/.bash_profile
#

[[ -f ~/.bashrc ]] && . ~/.bashrc

# first test that X hasn't launched
ps aux|grep -v grep|grep "/usr/lib/Xorg" >& /dev/null
EXITSTATUS=$?
if [ $EXITSTATUS -eq 1 ]; then
  echo "Going to startx in 8 seconds"
  read -t 8 -p "- enter any alphanumeric to abort : " keyhit
  if [ $keyhit ]; then
    echo "okay, startx yourself when ready"
  else
    [[ -z $DISPLAY && $XDG_VTNR -eq 1 ]] && startx
  fi
fi

