" vim: fdl=1:

" $machBld/jo/gvimrc  symlinked in  $bSc/symlinks/jo-0.sh

""> 0 monitor height
let g:monitorheight='768' " used in  $vimfiles/gvimrc.vim

""> 1 move on to  $vimfiles/gvimrc-Arch.vim
let gvimrcArch = expand("$HOME/.vim/gvimrc-Arch.vim")
if filereadable(gvimrcArch)
  exec "source ".gvimrcArch
endif " ignored if ~/.vim isn't yet there

