" vim: fdl=1:

" $machBld/jo/gvimrc  symlinked in  $OSAB/nodes-set/jo-0.sh

""> 0 monitor height
let g:monitorheight='900' " used in  $vimfiles/gvimrc.vim

""> 1 move on to  $vimfiles/gvimrc-Arch.vim
source $vimfiles/vim/enter/gvimrc-Arch.vim

