# vim: set ft=sh tw=0:

# ~/.bashrc in an Arch install on my Acer Veriton T661 system

# Joseph Harriott
# source ~/.bashrc if you've changed something here...

[[ $- != *i* ]] && return  # if not running interactively, don't do anything

if [[ $ARCHBUILDS ]]; then
    # 1 useful everywhere
    source $ARCHBUILDS/Bash/bashrc-generic
    # 2 useful also in Console
    source $ARCHBUILDS/jo/Bash/bashrc-console
fi

