#!/bin/sh

# JH note:
#  symlink this to  ~/.xinitrc  so that it is used instead of the default
#  my additions are marked JH

# copied from the default  /etc/X11/xinit/xinitrc
# -----------------------------------------------
userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# JH additions
# ------------
# defined here so they can be accessed by any KDE settings and by  gvim
# kill tmux sessions if you've made changes here
export DROPBOX=/home/jo/Dropbox   # keep this capitalised for finding it without need for $
    export ITstack=$DROPBOX/JH/IT_stack
        export onGH=$ITstack/onGitHub
            export ARCHBUILDS=$onGH/ArchBuilds
                export BAT_CONFIG_PATH=$ARCHBUILDS/jo/bat.conf  # for the bat pager
                export machineName=LTC-M58-7637
                    export MACHINE=$ARCHBUILDS/$machineName
                export Imagey=$ARCHBUILDS/jo/Bash/Imagey

userresources=$MACHINE/jo/Xresources

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# twm &
# xclock -geometry 50x50-1+1 &
# xterm -geometry 80x50+494+51 &
# xterm -geometry 80x20+494-0 &
# exec xterm -geometry 80x66+0+0 -name login

# ------------
# JH additions
# ------------

# stop the 600s screensaver
# xset s off

xbindkeys  # for mouse middle-click

# launch KDE
exec startplasma-x11

