#!/bin/bash
# vim: fdl=1 ft=sh:

# machine-specific exports that could also be useful as root

# for jo:
#  symlinked in  $ARCHBUILDS/build-scripts/17-symlinks.sh
#  sourced by  $Bash/bash_profile
# for root:
#  symlinked in  $ARCHBUILDS/build-scripts/05-root_symlinks.sh
#  sourced by  $ARCHBUILDS/root/bash_profile

export rsnapshot=/mnt/ST4000VN008/rsnapshot
export startxDelay=5

#=> for  $ARCHBUILDS/Bash/export-storage
export myDrA=1  # my Dropbox is active
export Storage=/mnt/WD30EZRZ  # where I keep stuff
    export me=$Storage/local/Encrypted

