
# MPD configuration file

# $ABjo/music/MPD/mpd.conf
#  based on  /usr/share/doc/mpd/mpdconf.example
#  symlinked in  $OSAB/nodes-set/jo-2-whenWM-1.sh
#   pb ~/.mpd/mpd.conf
#  maybe  systemctl --user restart mpd.service  if changes here

audio_output {
	type  "pulse"
	name  "pulse audio"
}
# - PulseAudio

auto_update "yes"
db_file "~/.config/mpd/database"
filesystem_charset  "UTF-8"
log_file "~/.config/mpd/log"
music_directory "~/music"
# - also finds hidden music files!

# for debugging
#log_level "verbose"

# for recovering last state
state_file "~/.config/mpd/state"

# for use of  mpd --kill  and some init scripts
pid_file "~/.config/mpd/pid"

# pause when restored
restore_paused "yes"

# -------
# -------
# max_...
# -------
# -------
# kb's here must be quoted, "n MiB" not accepted

# -------------------------------------
# avoid  vimpc "En: ..." when 36k files
# -------------------------------------
# find -L ~/music | wc -l

# "E3: Disabling database..."
max_output_buffer_size "16384"
# =  bc <<< 8192*2

# "E2: MPD Error: Playlist is too large"
max_playlist_length "65536"
# =  bc <<< 16384*4

