# vim: set ft=sh:

# get my  .bashrc  settings working in  Console  &  su
# cp $OSAB/root/bash_profile /root/.bash_profile

source ~/.export-machine; source ~/.export-storage

[[ -f /root/.bashrc ]] && . /root/.bashrc

. ~/.config/broot/launcher/bash/br  # - carries through to X

