# vim: set ft=sh tw=0:
#
# ~/.bash_profile
# get my  .bashrc  settings working in  Console
#

export DROPBOX=/mnt/SDSSDA240G/Dropbox
    export ITstack=$DROPBOX/JH/IT_stack
        export ARCHBUILDS=$ITstack/onGitHub/ArchBuilds
            [[ -f /root/.bashrc ]] && . /root/.bashrc  # needed for su

