#!/bin/bash
# vim: fdl=1 ft=sh sw=2:

# $machBld/jo/Bash/bashrc  symlinked in  $OSAB/bs-symlinks/jo-0.sh  e -la ~/.bashrc

[[ $- != *i* ]] && return  # if not running interactively, don't do anything

export CHROOT=/mnt/SD480GSSDPlus/chroot

#=> 0 load the rest of my bashrc
source $AjB/bashrc

#=> 0 various video directories
# echo -e "/mnt/ST4000VN008\n/mnt/SDU3D1TB\n/mnt/WD1001FALS" > $machBld/jo/Bash/VsLmore
#  used in  $ulL/video/OBSmkv/shrink.sh  &  fv()
export vlogs=$Storage/Sync2/AV-Stack/vlogs

#=> 1 OBS mkv grabs convert
# for  $ulL/video/OBSmkv/shrink.sh
# alias Ni="figlet -t -f nancyj 'Now ignore ...?'"
Ni () { echo; figlet -t -f nancyj '... now ignore ...'; }
ignore () { stat -c '%Y  %s  %n' "$1" >> $ulL/video/OBSmkv/ignore; }
# ignore <an_mkv_to_ignore>
# for m in *.mkv; do ignore "$m"; done

# $OBSmkvGrabs  is exported in  $machBld/export-machine
export OBSmkvGrabsConverted='/mnt/SDU3D1TB/stack/AV/OBSmkvGrabsConverted'

omc() {
  bash $ulL/video/OBSmkv/shrink.sh
  cd $OBSmkvGrabs  # useful if an exit occured
  fin
} # used in  $OSAB/sbMb/jo/autostart.sh

