#!/bin/bash
# vim: fdl=1 ft=sh:

# called by  $Bash/export-jo
# definitions here are used by  $Openbox/openbox/autostart/urxvtl.sh

#=> set geometry appropriate for monitor
# open urxvt from left of screen, allowing room for 106 column gVim

# 1920x1080  screen:
export urxvtGeometry='122x78+0+0'  # urxvt -geometry '122x78+0+0' &
# for  ubuntumono 9  in  $Openbox/Xresources/Xresources

#=> start with session 1
# export tmuxStartSession='new -s 1'

