#!/bin/bash
# vim: fdl=1 ft=sh:

# $machBld/jo/Bash/exportWS  called by  $Bash/export-jo

# definitions here are used in
#  $Obc/autostart/terminal_launch.sh
#  $Obc/rc/rc_xml-mb_make.sh

#=> set  Alacritty  window
# used in  $Obc/autostart/terminal_launch.sh
export Awd='window.dimensions={columns=124,lines=78}'
export Awp='window.position={x=5,y=5}'

#=> set  Neovide  window
export Nvdg='--grid 109x72'
# 1920x1080  monitors
# UbuntuMono_Nerd_Font_Mono:  h8:72, h9:67
# used in
#  $Obc/autostart/autostart
#  $Obc/rc/rc_xml-mb_make.sh

#=> set  urxvt  geometry appropriate for monitor
# open urxvt from left of screen, allowing room for 106 column gVim

# 1920x1080  screen:
export urxvtGeometry='122x78+0+0'  # urxvt -geometry 122x78+0+0 &
# for  ubuntumono 9  in  $Openbox/Xresources/Xresources

