# vim: list:

# Tabs between elements!

# $machBld/etc/rsnapshot.conf
#  see  $OSAB/bs-1-into_jo/7-rsnapshot.sh
# Set:
#  sudo cp $machBld/etc/rsnapshot.conf /etc/rsnapshot.conf
#  rsnapshot configtest
# Check against the source:
#  $cGRs/d-unix-like/r-rsnapshot-rsnapshot/rsnapshot.conf.default.in
# Use:
#  see  $OSAB/QR/QR.md
#   doas rsnapshot sync &  # sync's from sources to  $rsnapshot/.sync
#    sudo find $rsnapshot/.sync | wc -l
#   doas rsnapshot aaa &  # rotates from  $rsnapshot.sync, using hard links
#    sudo find $rsnapshot/aaa.0 | wc -l
#    sudo find $rsnapshot/aaa.1 | wc -l

config_version	1.2

snapshot_root	/run/media/jo/9QG2FFEE/rsnapshot/
no_create_root	1

cmd_cp		/usr/bin/cp
cmd_rm		/usr/bin/rm
cmd_rsync	/usr/bin/rsync
cmd_logger	/usr/bin/logger
cmd_du		/usr/bin/du
cmd_rsnapshot_diff	/usr/bin/rsnapshot-diff

# Needing  dunst:
cmd_preexec	/usr/bin/sudo -u jo DISPLAY=:0 DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus dunstify "rsnapshot sync will start"
cmd_postexec	/usr/bin/sudo -u jo DISPLAY=:0 DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus dunstify -u critical "rsnapshot sync finished"
# grep cmd_p /etc/rsnapshot.conf

retain	aaa	10
retain	bbb	10
retain	ccc	10
retain	ddd	10

# Logs:
verbose		2
loglevel	3
logfile	/var/log/rsnapshot

# Prevent two instances:
lockfile	/var/run/rsnapshot.pid

sync_first	1

# Directories to backup:
backup	/home/		DOP3040D11S/
backup	/etc/		DOP3040D11S/
backup	/boot/		DOP3040D11S/
backup	/root/		DOP3040D11S/
backup	/usr/		DOP3040D11S/
backup	/var/		DOP3040D11S/

