" ----------------------------------------------------------------------------
" this is a pointer, on a GNU+Linux system, to my more portably located gvimrc
" ----------------------------------------------------------------------------
let g:monitorheight='1050' " for setting window height
source $HOME/.vim/gvimrc-Arch.vim

