#!/bin/bash
# vim: fdl=1 ft=sh:

# $machBld/jo/Bash/exportWS

# called by  $Bash/export-jo
# definitions here are used in
#  $Obc/autostart/terminal_launch.sh
#  $Obc/rc/rc_xml-mb_make.sh

#=> set  Alacritty  window
# used in  $Obc/autostart/terminal_launch.sh
export Awd='window.dimensions={columns=67,lines=64}'
# - columns:
#    68 is obviously too narrow, but allows  my  Neovide  with  Conky visible
#   110 allows my  gVim
#   110 allow  my  Neovide
export Awp='window.position={x=5,y=5}'

#=> set  Neovide  window
export Nvdg='--grid 109x59'  # UbuntuMono_Nerd_Font_Mono:  h9:59
# used in
#  $Obc/autostart/autostart
#  $Obc/rc/rc_xml-mb_make.sh

#=> set  urxvt  geometry appropriate for 1440x900 monitor
# open urxvt from left of screen, allowing room for 106 column gVim
export urxvtGeometry='104x64+0+0'  # urxvt -geometry '104x64+0+0' &
# for  ubuntumono 9  in  $Openbox/Xresources/Xresources

