#!/bin/bash
# vim: fdl=1 ft=sh:

# machine-specific exports that could also be useful as root

# for jo:
#  symlinked in  $OSAB/bs-symlinks/jo-0.sh
#  sourced by  $Bash/bash_profile
# for root:
#  symlinked in  $OSAB/bs-symlinks/root.sh
#  sourced by  $OSAB/root/bash_profile

export csm=i34G1TU02-clamscan
export rsnapshot=/run/media/jo/9QG2FFEE/rsnapshot/
# export rsnapshot=/run/media/jo/KDTG311282/rsnapshot/
export startxDelay=5

#=> for  $OSAB/Bash/export-storage
export myDrA=1  # only when my Dropbox is active
export Storage=/mnt/BX200  # where I keep stuff
    export Enc=$Storage/encrypted  # $Enc

