# vim: list:

# Tabs between elements!

# See:
#  $nDrGRs/d-unix-like/r-rsnapshot-rsnapshot/rsnapshot.conf.default.in
#  $OSAB/bs-5-when_myDrA/rsnapshot.sh

# Set:
#  sudo cp $ABnm/etc/rsnapshot.conf /etc/rsnapshot.conf
#  rsnapshot configtest
#
# Use:  $ABno/rsnapshot
#  see  $OSAB/QR/QR.md

config_version	1.2

snapshot_root	/mnt/WD1001FALS/rsnapshot/
no_create_root	1

cmd_cp		/usr/bin/cp
cmd_rm		/usr/bin/rm
cmd_rsync	/usr/bin/rsync
cmd_logger	/usr/bin/logger
cmd_du		/usr/bin/du
cmd_rsnapshot_diff	/usr/bin/rsnapshot-diff

retain	aaa	10
retain	bbb	10
retain	ccc	10
retain	ddd	10

# Logs:
verbose		2
loglevel	3
logfile	/var/log/rsnapshot

# Prevent two instances:
lockfile	/var/run/rsnapshot.pid

sync_first	1

# Directories to backup:
backup	/home/		sbMb/
backup	/etc/		sbMb/
backup	/boot/		sbMb/
backup	/mnt/SDU3D1TB/Dropbox/devSh/	sbMb/
backup	/mnt/SDU3D1TB/Dropbox/IT/	sbMb/
backup	/mnt/SDU3D1TB/Dropbox/IT-culLAh/	sbMb/
backup	/mnt/SDU3D1TB/Dropbox/Jo/	sbMb/
backup	/mnt/SDU3D1TB/Dropbox/Photos/	sbMb/
backup	/mnt/SDU3D1TB/Dropbox/search/	sbMb/
backup	/root/		sbMb/
backup	/usr/		sbMb/
backup	/var/		sbMb/
# more  $Drpbx  directories handled by  $onGH/FM-rsync-drives/rsync0-WD30EZRZ.sh

