#!/bin/bash
# vim: ft=sh sw=2:

# $AjB/bashrc-console  symlinked in  $OSAB/nodes/set/jo-0.sh
#  then sourced by  $AjB/bash_profile  &  $machBld/jo/Bash/bashrc
# see  $OSAB/nodes-set/repair.sh  for checking if this was sourced

# useful also in Console as user

# -----------------------------------------------------------
# These are more settings that can also be useful in Console.
# -----------------------------------------------------------

# Joseph Harriott, Sat 14 Feb 2026

export SUDO_PROMPT="$(tput setab 1 setaf 7 bold)[sudo]$(tput sgr0) $(tput setaf 6)password for$(tput sgr0) $(tput setaf 5)%p$(tput sgr0): "
T (){ emacs -nw $1; }  # in terminal

ra () {
  pactl set-sink-volume 0 60%  # master volume to non-distorting level
  if [ $1 ]; then o=$1; else o=a; fi
  rec -c 2 $o.flac  # SoX
}; export -f ra  # ra <stereoAudioRecording>

#=> Bash interface
alias o=echo

# bigger command history
export HISTFILESIZE=20000  # lines
export HISTSIZE=1000  # commands
# defaults are 500

# command not found hook
source /usr/share/doc/pkgfile/command-not-found.bash

# for nnn & tmux
export EDITOR=nvim
export VISUAL=gvim

# pipx shell completions
eval "$(register-python-argcomplete pipx)"

# prompt
source "/usr/share/git/completion/git-prompt.sh"; source $OSL/nodes/bashrc-console-prompt

#=> file manage
alias rsA0='bash $onGH/rsync-portabledrives/rsync-Dr0archive.sh'
alias rsA1='bash $onGH/rsync-portabledrives/rsync-Dr1archive.sh'
alias v=vifm
source $OSL/nodes/bashrc-console-fm

C (){
  if [ $1 ]; then
    CliFM -A $1
  else
    CliFM -A .
  fi
}  # CliFM (show hidden)
CliFM (){
  clifm --cd-on-quit --disk-usage --rl-vi-mode --trash-as-rm "$@"
  dir="$(grep "^\*" "/home/jo/.config/clifm/.last" 2>/dev/null | cut -d':' -f2)";
  [ -d "$dir" ] && cd -- "$dir"
} # C <dir1> [<dir2> ...]

fRs () {
  echo "${tpf2}directory${tpfn}: $1"
  echo "${tpf2}glob to find${tpfn}: $2"
  if [ "$3" ]; then
    echo "${tpf2}not recursive${tpfn}"
    nodepth='-maxdepth 1 -mindepth 1'
  fi  # probably much faster
  echo
  if [ "$2" ]; then
    tf="$rsnapshot/tds_find"
    echo 'vim: nowrap:' > $tf; echo >> $tf; echo "$1 $2" >> $tf; echo >> $tf
    find $rsnapshot -maxdepth 1 -mindepth 1 -type d -name "$y*" | sort -V | while read -r rsd; do
      tput cuu 1; tput el; echo "${tpf5}searching in $rsd${tpfn}"; sleep .3
      find $rsd/localhost$1 $nodepth -name "*$2*" -printf %TY-%Tm-%Td\ %TH:%TM\ %p\\n 2> /dev/null | sort >> $tf
    done
    echo "${tpf2}- now look in  \$rsnapshot/tds_find${tpfn}"
  else
    echo "fdtsRsnapshot <directoryToSearchIn> <fileToSearchFor>"
  fi
} # no spaces in arguments

if [ -s "/usr/bin/zoxide" ]; then
  eval "$(zoxide init bash)"  # o $PROMPT_COMMAND
  zf () { cd "$(zoxide query -l | fzf -0 -1)"; } # then begin typing
  zq () { zoxide query -ls | grep -i $1; }
fi

dcp (){
    dcpo="$machLg/dircolors-p.txt"
    echo '# vim: ft=dircolors:' > $dcpo
    echo '' >> $dcpo
    dircolors -p >> $dcpo
    echo '' >> $dcpo
}

skl () { sk --ansi -i -c 'rg --color=always --line-number "{}"'; } # for finding text in files

#==> Git
alias ga='git add'
alias gsbs='git status -bs'
alias gsu='git status -u'
export BFG=$cITCP/bfg-1.13.0.jar
gic () { git commit -m "$1"; }

fgc () {
  gcf=dts-git_config.fgc
  echo '' > $gcf
  for f in $(fd -HI -tf ^config$); do sm $f; done | sort >> $gcf
  echo "results are in $gcf"
} # $Drpbx/JH/search/dts-git_config.fgc  using  $vfv/syntax/fgc.vim

lg() {
  export LAZYGIT_NEW_DIR_FILE=~/.lazygit/newdir
  lazygit "$@"
  if [ -f $LAZYGIT_NEW_DIR_FILE ]; then
    cd "$(cat $LAZYGIT_NEW_DIR_FILE)"
    rm -f $LAZYGIT_NEW_DIR_FILE > /dev/null
  fi }
# recommended in  $cGRs/d-CP/d-encoding/r-jesseduffield-lazygit/README.md
# ($cGRs/d-CP/d-encoding/r-jesseduffield-lazygit/pkg/gui/controllers/helpers/record_directory_helper.go)
# but I can't see it doing anything...

#===> time-sorted - my GitHub issues
ghi () {
  ghil=GitHubIssues.ffl
  for ITd in $jtIT $coreIT; do
    cd $ITd
    for f in $(rg -l -tmd 'github.com.+issues'); do sm $f; done | sort > $ghil
    sed -i '/copied\/IT-handy\//d' $ghil
    sed -i '1s/^/\n/' $ghil
    echo '' >> $ghil
    echo "results are in $ITd/$ghil"
  done
}
# $coreIT/GitHubIssues.ffl
# $jtIT/GitHubIssues.ffl

#==> lists of files by content
alias rgo="rg --field-match-separator ':::'"
# rgo rsync $DJH > $DJH/search/rsync.rgo ($vfv/syntax/rgo.vim)

rgIT () {
  cd $DJH/search
  f=IT-rg.ffl  # $DJH/search/IT-rg.ffl
  echo '' > $f
  for ITd in $jtIT $coreIT; do
    rgc="rg -l $1 $ITd"
    echo '' >> $f; echo $rgc >> $f
    echo '' >> $f; $rgc >> $f; echo '' >> $f
  done
  echo "- now open  $DJH/search/IT-rg.ffl"
} # rgIT <text_to_find_in_many_filetypes>

SE () {
  cd $DJH/search
  f=SEN.ffl
  [ -s $f ] && rm $f
  echo '' > $f; echo 'SE  -see  $AjB/bashrc-console'
  for ITd in $jtIT $coreIT $JHw/France; do
    echo '' >> $f
    rg -l -tmd 'stackexchange|stackoverflow|superuser' $ITd | sort >> $f
  done
  echo '' >> $f
  echo 'now open $DJH/search/'$f
} # /stackexchange\|stackoverflow\|superuser

#==> my Arch Forum issues
# $DJH/search

fbbcode () {
  bbcf='fbbcode.ffl'
  echo "" > $bbcf; echo $PWD >> $bbcf; echo "" >> $bbcf
  fdb='fd -tf -e bbcode'
  { echo $fdb; echo; } >> $bbcf
  $fdb >> $bbcf; echo >> $bbcf
  rgb="rg -ttxt -l --sort modified 'ft=bbcode'"
  { echo $rgb; echo; } >> $bbcf
  eval $rgb >> $bbcf; echo >> $bbcf
  echo "results are in $bbcf"
} # $DJH; fbbcode

#==> my Encrypted directories
# fa  defined in  $OSL/bashrc-console-fm
# in  $Enc
#  fa | grep Digital0
#  fa | grep Secure0
#  fa | grep Secure1
#  fa | grep Stack

#===> Encrypted Changes
Encrypted=(Czm Digital0 Digital1 Secure0 Secure1 SHG Stack)
EC0 () {
  if [ "$PWD" != $Enc ]; then
    if [ -d "$Enc" ]; then cd $Enc; pwd; else echo "$Enc ain't there"; return; fi
  fi
}
EC1 () {
  EC0
  cel="$core/encrypted/last"
  lr=$(tail -1 $cel) # last recorded
  lrts=${lr:0:17}; echo "last: $lrts"
  mapfile -t ll < <(find . ! -wholename '*/.git/*' -printf %TY%Tm%Td-%TH:%TM:%.2TS\ %p\\n | sort) # local list
  # echo ${#ll[@]}  # number of elements
  lll=${ll[-1]:0:17}; echo "here: $lll"
  if [[ ${lll} > ${lrts} ]]; then
    echo "# $(uname -n)" >> $cel
    printf '%s\n' "${ll[@]}" >> $cel
  fi
}
EC2 () {
  EC0
  for E in ${Encrypted[@]}; do
    # o $E
    f7z="find . -iname \"$E*.7z\" | sort | tail -1"
    ed7z=$(eval "$f7z")
    if [ $ed7z ]; then
      # En = $Enc
        mapfile -t all < <(find . -iname "$E*.7z" -printf %TY-%Tm-%Td\ %TH:%TM\ En\ %P\\n | sort)
        mapfile -t ch < <(find -path "./$E*" -newer $ed7z -printf %TY-%Tm-%Td\ %TH:%TM\ En\ %P\\n | sort) # changes
        all+=("${ch[@]}")
      # ce = $core/encrypted
        mapfile -t ce < <(find "$core/encrypted" -name "$E*" -printf %TY-%Tm-%Td\ %TH:%TM\ ce\ %P\\n) # $core/encrypted
        all+=("${ce[@]}")
      printf '%s\n' "${all[@]}" | sort
    fi
  done
}

#=> human language - dict
alias del='dict -d elements'  # del iron

# English:
alias dmt='dict -d moby-thesaurus'  # dmt fuck
alias dwn='dict -d wn'  # dwn fuck

# French translate
alias def='dict -d fd-eng-fra'  # def fuck
alias dfe='dict -d fd-fra-eng'  # dfe facture

#=> human language - Verbiste
alias decon='french-deconjugator'  # decon aimâmes

con () {
  fco="$(french-conjugator "$1")"
  oneline="${fco//$'\n'/ }"
  trimmed="$(echo "$oneline" | cut -c 3- | rev | cut -c 3- | rev)"
  flagged="${trimmed//$' - '/≡}"
  IFS="≡" read -r -a array <<< "$flagged"
  for conjugation in "${array[@]}"; do
    tense="$(echo "$conjugation" | sed 's/:.\+//')"
    conjugations="$(echo "$conjugation" | sed 's/.\+: //')"
    spaced="$(echo "$conjugations" | sed 's/ /  /g')"
    echo -e "\e[32m $tense \e[1;33m $spaced \e[0m"
  done
} # con <a_French_infinitive>, con être

#=> npm global directory
export PATH="$HOME/.npm-global/bin:$PATH"

#=> pipx exposed binaries
export PATH="$PATH:$HOME/.local/bin"  # for  pipx  installed commands

#=> Ruby gems
if [ -s "/usr/bin/ruby" ]; then
  export GEM_HOME="$(ruby -e 'puts Gem.user_dir')"
  export PATH="$PATH:$GEM_HOME/bin"
fi

#=> system
alias i=pinfo
alias im='pinfo -m'
export GPG_TTY=$(tty)  # correct TTY for GnuPG

#==> for AUR packages
# "Get Clone To Make" - for my building of AUR development packages
gctm(){ cd $HOME/Arch/AURdev-make; rAUR $1; cp -r ../AURdev-clone/$1 $1; cd $1; }; export -f gctm

# get into an AUR repository
gAUR () { cd "$HOME/Arch/AUR$2"; rAUR $1; trizen -G $1; cd $1; }; export -f gAUR
# $2  is for  gdAUR
# if fail to enter pw in time for trizen, pacman -U package_name-version.pkg.tar.xz

# get into an AUR development repository
gdAUR () { gAUR $1 dev-clone; gctm $1; }; export -f gdAUR

# remove an AUR repository if it's there
rAUR(){ [ -d $1 ] && sudo rm -r $1; }; export -f rAUR

#=> text wrangling
nn () { nvim $@; cd $(cat ~/lastVimDirectory); } # see  $vfv/enter/vimrc.vim

# find conversions to latin1 in a directory
fcL1 () { sed -r '/(Â[^a-z]|Ã|Å|É[^a-z]|â[^,a-z])/!d' $1 > "${1/./_}-latin1.txt"; }
# /\v<contents_of_those_braces>

