# vim: fdl=2 ft=sh sw=2:

# $AjB/bashrc, sourced by  $machBld/jo/Bash/bashrc

#=> 0 up to Console
# $AjB/bash_profile  ensured the exports
  source $OSAB/nodes-Bash/bashrc-generic
  #   source $AjB/bashrc-console  # sources  $OSL/nodes/bashrc-console-fm
  source ~/.bashrc-console  # $AjB/bashrc-console

#=> 1 up to terminal
source $AjB/bashrc-terminal

#=> 2 when in WM
source $AjB/bashrc-wm
source $OSL/nodes/bashrc-clm  # can be used before WM

#=> 3 ble.sh, Atuin
source $OSAB/nodes-Bash/ble-atuin

