#!/bin/bash
# vim: fdl=1 ft=sh:

# $machBld/Bash_start

# machine-specific exports that could also be useful as root

# for jo:
#  symlinked in  $OSAB/nodes-set/jo-0-Bash-X.sh
#  sourced by  $AjB/bash_profile
# for root:
#  symlinked in  $OSAB/nodes-set/root.sh
#  sourced by  $OSAB/nodes-root/bash_profile

export rsnapshot=/run/media/jo/9QG2FFEE/rsnapshot/  # $rsnapshot
export startxDelay=5

#=> for  $OSAB/nodes-Bash/export-Arch
export myDrA=1  # $myDrA, only when my Dropbox is active
export Storage=/mnt/BX200  # where I keep stuff
    export Enc=$Storage/encrypted  # mkdir $Enc

