#!/bin/bash
# vim: fdl=1 ft=sh:

# $machBld/export-machine

# machine-specific exports that could also be useful as root

# for jo:
#  symlinked in  $OSAB/nodes-set/jo-0.sh
#  sourced by  $AjB/bash_profile
# for root:
#  symlinked in  $OSAB/nodes-set/root.sh
#  sourced by  $OSAB/nodes-root/bash_profile

export csm=DOP3040D11S-clamscan
export rsnapshot=/run/media/jo/9QG2FFEE/rsnapshot/  # $rsnapshot
export startxDelay=5

#=> for  $OSAB/nodes-Bash/export-storage
export myDrA=1  # only when my Dropbox is active
export Storage=/mnt/BX200  # where I keep stuff
    export Enc=$Storage/encrypted  # mkdir $Enc

