# vim: ft=sh.shfold sw=2:

# ~/.bashrc in an Arch install on my Acer Veriton T661 system

# Joseph Harriott
# source ~/.bashrc if you've changed something here...

[[ $- != *i* ]] && return  # if not running interactively, don't do anything
export LIBVA_DRIVER_NAME=i965
export MESA_GLSL_CACHE_DISABLE=true

#=> auto-added by $ cpan
PATH="/home/jo/perl5/bin${PATH:+:${PATH}}"; export PATH;
PERL5LIB="/home/jo/perl5/lib/perl5${PERL5LIB:+:${PERL5LIB}}"; export PERL5LIB;
PERL_LOCAL_LIB_ROOT="/home/jo/perl5${PERL_LOCAL_LIB_ROOT:+:${PERL_LOCAL_LIB_ROOT}}"; export PERL_LOCAL_LIB_ROOT;
PERL_MB_OPT="--install_base \"/home/jo/perl5\""; export PERL_MB_OPT;
PERL_MM_OPT="INSTALL_BASE=/home/jo/perl5"; export PERL_MM_OPT;

# #=> iwd NETGEAR WG111v2
# doup () {
#   sudo ip link set wlwg111v2 down
#   sudo ip link set wlwg111v2 up
# } # often needed...
# alias d='doup'

# alias i='iwctl station wlwg111v2 get-networks'

# # sudo dhcpcd wlwg111v2  # might be needed
# # sudo dhcpcd -k wlwg111v2

#=> load the rest of my bashrc
source $ARCHBUILDS/Bash/bashrc-generic  # useful everywhere, including root
source $Bash/bashrc-console  # useful also in Console as user
source $Bash/bashrc-email  # can be used before WM
source $Bash/bashrc-wm
source $Bash/bashrc-ob  # useful in Openbox

