#!/bin/sh

# sourced by  $Bash/bash_profile
# symlink this to  ~/.export-machine

export machine=M587637
export Storage=/mnt/SDSSDA240G  # where I keep stuff

# Used in  $Openbox/openbox/urxvtl.sh
# open urxvt from left of screen, allowing room for 106 column gVim
# export urxvtGeometry='81x46+0+0'  # 1366x768 screen
export urxvtGeometry='92x54+0+0'  # 1440x900 screen

