#!/bin/sh

# sourced by  ~/.xinitrc
# symlink this to  ~/.xinitrc-exports
# Each machine needs its own version of this configuration file.

# defined here so they can be accessed by  $MACHINE/jo/Openbox/autostart  & by  gvim
# kill tmux sessions if you've made changes here
export machine=M587637
export Storage=/mnt/SDSSDA240G  # where I keep stuff
    export DROPBOX=$Storage/Dropbox   # keep this capitalised for finding it without need for $
        export ITstack=$DROPBOX/JH/core/IT_stack
            # two private configurations:
            export CrossPlatform=$ITstack/CrossPlatform
            export GNULE=$ITstack/unix_like/email-GNULinux
        export onGH=$DROPBOX/JH/core/IT_stack/onGitHub
            export ARCHBUILDS=$HOME/ArchBuilds # provisional
            export ARCHBUILDS=$onGH/ArchBuilds # once Dropbox is up
                export BAT_CONFIG_PATH=$ARCHBUILDS/jo/bat.conf  # for the bat pager
                export Bash=$ARCHBUILDS/jo/Bash
                    export Imagey=$Bash/Imagey
                    export MACHINE=$ARCHBUILDS/$machine
                export Openbox=$ARCHBUILDS/jo/Openbox
                    export email=$ARCHBUILDS/jo/mail  # used in  bashrc-email  and  muttrc-*
                    export tmux=$ARCHBUILDS/jo/tmux  # used in tmux.conf
            export MD4PDF=$onGH/md4pdf
        export IThandy=$DROPBOX/JH/Copied/IT-handy  # for fonts
        export ITHD=$DROPBOX/JH/Technos/IT0-HD  # $ITHD/diskUsage.txt
        export SE=$DROPBOX/JH/CforWork/Education/Science-Engineering  # used in my TextNotes
