#!/bin/sh

# JH note:
#  symlink this to  ~/.xinitrc  so that it is used instead of the default
#  I built this from default, with my additions marked JH.
#  Each machine needs its own version of this configuration file.

# copied from the default  /etc/X11/xinit/xinitrc
# -----------------------------------------------
userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# JH additions
# ------------
userresources=$MACHINE/jo/Xresources  # space after the = for vim gf

# copied from the default  /etc/X11/xinit/xinitrc
# -----------------------------------------------
# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# twm &
# xclock -geometry 50x50-1+1 &
# xterm -geometry 80x50+494+51 &
# xterm -geometry 80x20+494-0 &
# exec xterm -geometry 80x66+0+0 -name login

# JH additions
# ------------

# stop the 600s screensaver
xset s off

# lastly, Openbox
export QT_QPA_PLATFORMTHEME=qt5ct # QPA set here so qt5ct works from Menu too
xbindkeys  # must be before launching Openbox
exec openbox-session

