#!/bin/bash
# vim: fdl=1 ft=sh sw=2:

# ~/.bashrc in an Arch install on my sprayed brown Multivision box system

# Joseph Harriott
# source ~/.bashrc if you've changed something here...

[[ $- != *i* ]] && return  # if not running interactively, don't do anything

export VsLocation=/mnt/ST4000VN008  # path to my video store

omc() # OBS mkv grabs convert
{
    cd $VsLocation/OBSmkvGrabs
    echo "(moved to $PWD to run OBSmkvShrink.sh)"
    bash shrink.sh
}

#=> load the rest of my bashrc
source ~/.bashrc-generic  # useful everywhere, including root
source ~/.bashrc-console  # useful also in Console as user
source $Bash/bashrc-email  # can be used before WM
source $Bash/bashrc-wm
source $Bash/bashrc-ob  # useful in Openbox

