#!/bin/bash
# vim: ft=sh:

# sourced by  $ARCHBUILDS/jo/export-storage
#  which is sourced by  $Bash/bash_profile

# Used in  $Openbox/openbox/urxvtl.sh
# open urxvt from left of screen, allowing room for 106 column gVim
# export urxvtGeometry='92x54+0+0'  # 1440x900 screen
export urxvtGeometry='105x67+0+0'  # 1920x1080 screen:  urxvt -geometry '105x67+0+0' &

