# vim: set ft=sh tw=0:

# ~/.bashrc in an Arch install on my sprayed brown Multivision box system

# Joseph Harriott
# source ~/.bashrc if you've changed something here...

[[ $- != *i* ]] && return  # if not running interactively, don't do anything

# the following source commands are tweaked for each Bash case
brcConsole () {
    # bashrc 1 - useful everywhere, including root
    source $ARCHBUILDS/Bash/bashrc-generic
    # bashrc 2 - useful also in Console as user
    source $Bash/bashrc-console
}
if [[ $ARCHBUILDS ]]; then  # it's been defined in ~/.xinitrc
    brcConsole
    # bashrc 3 - useful only for jo
    source $Bash/bashrc-email
    source $Bash/bashrc-wm
    source $Bash/bashrc-ob
else                        # try a local cache
    ARCHBUILDS=~/ArchBuilds
    [[ -d $ARCHBUILDS ]] && brcConsole
fi

