# vim: fdl=1 ft=sh.shfold sw=2:

# ~/.bashrc in an Arch install on my sprayed brown Multivision box system

# Joseph Harriott
# source ~/.bashrc if you've changed something here...

[[ $- != *i* ]] && return  # if not running interactively, don't do anything

export VsLocation=/mnt/WD30EZRZ  # path to my video store

#=> load the rest of my bashrc
source $ARCHBUILDS/Bash/bashrc-generic  # useful everywhere, including root
source $Bash/bashrc-console  # useful also in Console as user
source $Bash/bashrc-email  # can be used before WM
source $Bash/bashrc-wm
source $Bash/bashrc-ob  # useful in Openbox

