#!/bin/sh
# vim: fdl=1 ft=sh:

# sourced by  $Bash/bash_profile
# symlink this to  ~/.export-machine

export machine=sbMb
export Storage=/mnt/SD480GSSDPlus  # where I keep stuff

# Used in  $Openbox/openbox/urxvtl.sh
# open urxvt from left of screen, allowing room for 106 column gVim
# export urxvtGeometry='92x54+0+0'  # 1440x900 screen
export urxvtGeometry='105x67+0+0'  # 1920x1080 screen:  urxvt -geometry '105x67+0+0' &

