#!/bin/sh
# vim: fdl=2 ft=sh sw=2:

# here I export variables that could also be useful as root
# . $ARCHBUILDS/Bash/export-storage

# Variable naming constraints:
#  avoid names that only differ by case
#  use names that grep unambiguously

# for initial build of Arch:
# for jo:
#  symlinked in  $bs/anytime/symlinks-jo.sh
#  sourced by  $Bash/bash_profile
# for root:
#  symlinked in  $bs/anytime/symlinks-root.sh
#  sourced by  $ARCHBUILDS/root/bash_profile

export host=$(uname -n)
# - for  $ARCHBUILDS/jo/Openbox/conkyrc  &  $ARCHBUILDS/Bash/bashrc-generic

#=> 0 core
# $myDrA  &  $Storage  are pre-defined in  $MACHINE/export-machine

#==> 0 $DROPBOX
if [[ $Storage ]]; then
  export DROPBOX=$Storage/Dropbox
  # - keep  DROPBOX  capitalised for finding it without need for $
  export core=$DROPBOX/JH/core
    export ITstack=$core/IT_stack
      export CP=$ITstack/CrossPlatform  # used in  $Bash/bashrc-console  & build scripts
      export ulL=$ITstack/unix_like-linux  # was $ulGL
        export lB=$ulL/Bash  # used in  $ARCHBUILDS/QR.txt
      export onGH=$ITstack/onGitHub
        export vimfiles=$onGH/vimfiles
fi

#==> 2 $ARCHBUILDS
unset ARCHBUILDS
if [ $onGH ]; then
  export ARCHBUILDS=$onGH/ArchBuilds
else
  AB=~/ArchBuilds; if [ -d $AB ]; then export ARCHBUILDS=$AB
  hjAB=/home/jo/ArchBuilds; elif [ -d $hjAB ]; then export ARCHBUILDS=$hjAB
  fi  # provisional
fi
if [ $ARCHBUILDS ]; then
  export BAT_CONFIG_PATH=$ARCHBUILDS/jo/bat.conf  # for the bat pager
  export Bash=$ARCHBUILDS/jo/Bash
  export bs=$ARCHBUILDS/build-scripts
      export MACHINE=$ARCHBUILDS/$host
  export clm=$ARCHBUILDS/jo/clm  # used in  bashrc-clm  and  muttrc-*  :s/email/clm/g
  export tmx=$ARCHBUILDS/tmux  # used in  tmux.conf
fi

#=> 0 mail
export maild=/home/jo/.local/share/mail  # used also in  muttrc-*

