#!/bin/sh
# vim: ft=sh sw=2:

# $OSAB/Bash/export-storage  (for  ~/.export-storage)
# here I export variables that could also be useful as root

# Variable naming constraints:
#  avoid names that only differ by case
#  use names that grep unambiguously throughout all of my notes directories

# for initial build of Arch (after $machBld/export-machine):
# for jo:
#  symlinked in  $OSAB/bs-symlinks/jo-0.sh
#  sourced by  $AjB/bash_profile
# for root:
#  symlinked in  $OSAB/bs-symlinks/root.sh
#  sourced by  $OSAB/root/bash_profile

#=> 0 core
# $myDrA  &  $Storage  are pre-defined in  $machBld/export-machine

#=> 0 mail
export maild=/home/jo/.local/share/mail  # $maild  for  mutt

#=> 1 host
export host=$(uname -n) # $host

#=> 2 $Drpbx, or not
export vimfiles=~/.vim
if [[ $myDrA == 1 ]]; then
  export Drpbx=$Storage/Dropbox
    export DJH=$Drpbx/JH
    # - keep  DROPBOX  capitalised for finding it without need for $
      export core=$DJH/core
        export ITstack=$core/IT_stack
          export CrPl=$ITstack/CP  # $CrPl  used in  $AjB/bashrc-console  & build scripts
          export onGH=$ITstack/onGitHub
            export vimfiles=$onGH/vimfiles
          export ulL=$ITstack/ulLinux
            export ulLA=$ulL/Arch
              export machLg=$ulLA/ml-$host  # as opposed to  $machBld
            export ulLB=$ulL/Bash  # used in  $OSAB/QR.md
          export ulLAb="$ITstack/ulLinuxArch-big" # $ulLAb
fi  # depends on  myDrA=  defined in  $machBld/export-machine

#=> 3 (rooting on $onGH) $OSAB, $OSL, and some build dependencies
unset OSAB, OSL
if [ $onGH ]; then
  export OSAB=$onGH/OS-ArchBuilds
  export OSL=$onGH/OS-Linux
else
  AB=~/OS-ArchBuilds; [ -d $AB ] && export OSAB=$AB
  hjAB=/home/jo/OS-ArchBuilds; [ -d $hjAB ] && export OSAB=$hjAB
fi  # depends on  onGH=
if [ $OSAB ]; then
  export ABjo=$OSAB/jo
    export AjB=$ABjo/Bash
    export BAT_CONFIG_PATH=$ABjo/bat.conf  # for the bat pager
    export clMail=$ABjo/clm  # used in  $AjB/bashrc-clm  and  $clMail/neomutt/muttrc-accounts/
  export machBld=$OSAB/mb-$host  # $machBld  as opposed to  $machLg
fi

