
# $machBld/jo/term/Alacritty/Xfce.toml ($OSAB/nodes-set/jo-3-when_myDrA.sh)

[font]
  size = 8  # change is instantaneous

[general]
  import = [ "~/.alacritty-all.toml" ] # $OSAB/nodes-terminal/alacritty-all.toml

