#!/bin/bash

# rc file for  $ABnm/.../term/Alacritty/AlNvim.sh
# source $ABjo/wm/Openbox/bashrc_for_Alacritty-nvim.sh
#  symlinked in  $OSAB/nodes-set/jo-0-Bash-X.sh
#   size dictated by  nvim

source ~/.bashrc  # $ABnm/.../bashrc
nn  # defined in  $AjB/bashrc-console

