# vim: fdl=1 ft=systemd:

# $OSAB/nodes-etc/systemd/autologin.conf
#  cp'd  in  my  $OSAB/bs-2-to_X/1-sudo-autoLoginTTY.sh
#  supersedes  $OSAB/nodes-etc/systemd/override.conf

[Service]
ExecStart=
ExecStart=-/sbin/agetty -o '-p -f -- \\u' --noclear --autologin jo - $TERM
# ExecStart=-/sbin/agetty -o '-p -f -- \\u' --keep-baud --autologin username 115200,57600,38400,9600 - $TERM

